### ISSUE TITLE
11/08 조교님 피드백

### ISSUE THREAD

**Issue by KyoungWan** [swsnu/swpp18-team1#15]
# TA's Feedback

### sprint 3.
총평 : 테스트 커버리지를 올려라

- 기능적인 부분은 많이 된 편이다.
- Design 문서도 좋았다.
- Indirect Layer를 만들어서 QR을 매시간마다 redirecting하게 하는 설계가 좋다.
  - 중간발표때 이를 구현/강조해서 발표하면 좋을것이다.
- 중간발표가 꽤 많은 비중(스프린트 총합보다)을 차지하므로 잘해야할듯
- 중간발표때 어디까지 할 수 있나?
  - 회원가입, DM등 기능적인부분을 완성 
  - Deploy하여 사람들이 그자리에서 참여해 볼 수 있도록
- 피쳐들을 추가하기 좋은 구조이다.
  - 100명 이상의 유저리스트를 보여줄때 lazy evaluation을 통해 천천히 로딩하기
  - 캐시에 저장하기 등

#### TODO
- [x] sprint마다 태그 붙이기 
- [x] progress report 작성
- [x] angular 테스트 작성

**Comment by sdu6342** [comment]
문서 수정 
## Model
Below is the ER diagram showing the columns and relationships of the model.
<img width="651" alt="2018-11-05 1 34 00" src="https://user-images.githubusercontent.com/18095606/47978494-8d801b00-e101-11e8-8320-f5de58147a4c.png">

### Model column description

- User: Email and password are used to sign up as a manager. When not in the manager, channel_id is the id of the channel the user is connected to. image is used as the profile image address.
- Channel: Manager_id is the id of the user managing the channel. Title is the name of the channel, and duration is the duration of the channel.
- DirectChannel: Sender_id is the id of the user who sent the direct message and receiver_id is the id of the user who received the direct message.
- ChannelMessage: The channel_id is the ID of the channel to which the message belongs. sender_id is the ID of the user who sent the message. content is the content of the message.
- DirectMessage: direct_channel_id is the ID value of the Direct Channel to which the message belongs. sender and content are the same as ChannelMessage.

### Relationship description

- When the user is a manager (is_manager = true), it has a 1: 1 relationship with the channel.
- When the user is not a manager (is_manager = false), it is a 1: N relationship with the Channel.
- User is 1: N relationship with Direct Channel sent from sender's point of view.
- User is a 1: N relationship with Direct Channel received from the perspective of the receiver.
- User and Channel Message are in 1: N relationship.
- User and Direct Message are in 1: N relationship.s
- User model is User: User using Direct Channel model is M: N relationship.
- Channel and ChannelMessage are in 1: N relationship
- Direct Channel and Direct Message are in 1:N relationship







### Backend design

For functions other than chatting, the data exchange between the frontend and the backend using the HTTP protocol consists of the following restful APIs.

| Model          | API                                  | GET                                            | POST               | PUT  | DELETE   |
| -------------- | ------------------------------------ | ---------------------------------------------- | ------------------ | ---- | -------- |
| User           | /user                                | x                                              | create new user    | x    | x        |
|                | /session                             | x                                              | sign in            | x    | sign out |
| Channel        | /channel/:channel_hash               | get specific channel                           | x                  | x    | x        |
|                | /channel                             | x                                              | create new channel | x    | x        |
| ChannelMessage | /channel/channel_hash/message        | get messages by channel_hash                   | x                  | x    | x        |
| DirectChannel  | /channel/channel_hash/direct_channel | get specific direct channels of user & channel | x                  | x    | x        |
| DirectMessage  | /direct_channel/:id/message          | get messages by direct_channel_id              | x                  | x    | x        |

**Comment by hwan517h1** [comment]
Sprint Progress Report 작성해서 보냈습니다!

**Comment by hwan517h1** [comment]
부족하지만 Angular Testing도 한 만큼만 올리겠습니다!
