### ISSUE TITLE
Design and Planning

### ISSUE THREAD

**Issue by sdu6342** [swsnu/swpp18-team1#6]
**참고 자료**
https://github.com/swsnu/swppfall2018/blob/master/project/design-and-planning-examples/Design_and_Planning_example.pdf

**To Do List**
- [x] 1.System Architecture : MVC @sdu6342 
- [x] 2.Model : ER-diagram(DB, Class) @sdu6342 
- [x] 3.View : all page & details @KyoungWan 
- [x] 4.Controller : data flow (client - server) using MVC @KyoungWan 
- [x] Design Detail
  - [x] 5.Frontend Components : Component(button, input etc), Subcomponent, Service, etc @hwan517h1 
  - [x] 6.Frontend Logics : 앞에서 사용된 로직들을 구체적으로 설명 @hwan517h1 
  - [x] 7.Frontend Relations : 어떤 버튼을 눌러서 뷰가 이동하는지 혹은 어떤 Service를 어떤 Component가 사용하는지 @hwan517h1 
   - [x] 8.API 명세서 : ResetFul + Websocket(새로운 Protocol 정의 필수) @sdu6342 

+ 위의 것들을 작성한 후, 밑의 2개는 같이 해야할 듯!
- [x] Implementation Plan : 스프린트 별로 할 일들 (#5 Spec문서에도 포함되어야 한다.)
- [x] Testing Plan

**Comment by sdu6342** [comment]
System Architecture : MVC
<img width="892" alt="2018-10-19 9 41 39" src="https://user-images.githubusercontent.com/18095606/47218777-dccb0980-d3e7-11e8-910c-9bee98a6e382.png">

System Architecture(Chat)
<img width="473" alt="2018-10-19 9 41 45" src="https://user-images.githubusercontent.com/18095606/47218794-e5bbdb00-d3e7-11e8-88ed-20f47f2c1fd8.png">

**Comment by hwan517h1** [comment]
**Frontend Design: Frontend Components**

![image](https://user-images.githubusercontent.com/37106318/47219118-da1ce400-d3e8-11e8-90c3-291065de503a.png)

**Comment by sdu6342** [comment]
### 2. Websocket Protocol
*requirements*
1. 유저가 채널에 접속해서 채널을 보고 있는 중에 채팅이 도착하거나 채팅을 보낼 경우 채널에 보지 않은 채팅이 생성되었음을 알려준다.
2. 유저(A)가 채널에 접속해 있고 다른 유저(B) 나 전체 채팅을 하고 있을 때 다른 유저(C)가 DM을 보내면 C와의 DM에 새로운 채팅이 있음을 알려준다.
3. 유저(A)가 채널에 접속해 있고 다른 유저(B)와 채팅을 하고 있을 때 B가 DM을 보내면 DM창에서 채팅내용을 확인 할 수 있다.
4. 유저가(A)가 채널에 접속해 있을 때 다른유저 B에게 DM을 보내면 A에게는 B에 대한 새로운 알람이 생성되지 않는다.
5. 유저가 메시지를 보냈는데 실패할 경우 메시지를 재전송하거나 취소 할 수 있는 버튼이 메시지 옆에 생성된다. 
6. 유저 A가 채널에 접속해 있을때, 새로운 유저 B가 접속하면 접속유저리스트에 B의 정보가 추가되어 A에게 보인다.

*주고 받는 패킷* 
```
{event: integer,
data : object
status: integer(보낸 메시지의 응답 결과일때만 존재함)
}
```
event는 보내는 요청 또는 응답이 무엇인지를 결정 해준다. data는 해당 이벤트의 결과 값이나 참고해야할 값을 내포한다.
다음의 리스트는 요청 또는 응답에 대한 event list 이다.

Client -> Server events(Request)
1. SendChannelMessage : 유저가 채널에서 메시지를 보내는 경우이다. 본인의 ID와 대화의 내용이 data에 포함된다. 
2. SendNewDirectMessage : 유저가 DirectMessage를 하고 있지 않던 다른 유저에게 메시지를 보내는 경우이다.  본인의 ID와 받는 유저의 ID, 대화 내용이 data에 포함된다.
2. SendDirectMessage : 유저가 DirectMessage를 하고 있던 유저에게 메시지를 보내는 경우이다. DM의 ID와 대화의 내용이 data에 포함된다.

Server -> Client events(Response)
1. ReceiveChannelMessage : 유저 A가 채널에 접속해 있을때 다른 유저 B가 채널에 대화를 입력했을 경우 A가 받는 패킷이다. data에는 받은 메시지의 내용과 메시지를 보낸 유저의 정보가 담겨 있다.
2. ReceiveDirectMessage : 이미 유저 B와 DM을 했었던 유저 A가 유저 B에게 DM을 받은 경우이다. data에는 받은 메시지의 내용과 DM의 ID가 있다.
3. ReceiveNewDirectMessage : 유저 B와 DM을 하지 않은 유저 A가 유저 B에게 DM을 받은 경우이다. data에는 받은 메시지의 내용과 DM을 보내는 유저의 Id가 있다.
4. MessageResult(메시지 성공여부) : 유저가 보낸 메시지의 성공 여부를 알 수 있는 패킷이다. data에는 유저가 보냈던 요청의 이벤트와, 보냈던 대화의 내용, 그리고 상태가 담겨있다.
메시지 상태는 메시지 패킷 parsing error, server connection error(redis?), 등등이 있다.
5. NewUserConnect(새로운 유저 등장) : 새로운 유저가 채널에 접속했음을 알려주는 패킷이다. data에는 새로 접속한 유저의 정보가 담긴다.
6. EndChannel(채널종료) : 채널의 기간이 끝났음을 알려주는 패킷이다. data에는 channel의 정보가 담긴다. 


**TODO : 패킷처리 에러에 대한 리스트 정리, 위 메시지 프로토콜이 최선인지 고민**
* 고민되는 것 : DM과 관련되어서 New를 구분해야만 하는가? *

**Comment by hwan517h1** [comment]
**Frontend Algorithms: Components** 

1. ManagerSignIn
- ngOnInit(): Call SignIn page with 2 inputs(email, password) and 3 buttons(sing_in, sign_up, about_us).
- onClickSignInButton(email: string, password: string): Call signIn in UserService. If sign-in is accepted, redirect to NewChannel page or Main page along the existence of channel. If sign-in is rejected, alert the warning message.
- onClickSignUpButton(): Redirect to ManagerSignUp page. - onClickAboutUsButton(): Redirect to AboutUs page.
2. ManagerSingUp
- ngOnInit(): Call SignUp page with 3 inputs(email, password, key) and 2 buttons(sign_up, about_us).
- onClickSignUpButton(email: string, password: string, key: string): Call signUp in UserService. If sign-up is accepted, redirected to SignIn page. If sign-up is rejected, alert the warning message. - onClickAboutUsButton(): Redirect to AboutUs page.
3. AboutUs
- ngOnInit(): Call AboutUs page with 1 text(description) and 1 button(back). - onClickBackButton(): Redirect to previous SignIn page.
4. NewChannel - ngOnInit(): Call NewChannel page with 2 inputs(channel_name, channel_duration) and 2 buttons(channel_create, sign_out).
- onClickChannelCreateButton(channel_name: string, channel_duration: string): Call createChannel in ChannelService. If channel-create is accepted, redirect to Main page. If channel-create is rejected, alert the warning message.
- onClickSignOutButton(): Sign out and redirect to SignIn page.
5. Main - ngOnInit(): Call Main page with 3 inputs(to_qr, to_chat, sign_out). - onClickToQRButton(): Redirect to ShowQR page.
- onClickToChannelButton(): Redirect to Channel page.
- onClickSignOutButton(): Sign out and redirect to SignIn page.
6. ShowQR - ngOnInit(): Call ShowQR page with 1 button(full_screen) and 1 text(description).
- onClickFullScreenButton(): Change ShowQR page into full screen.
7. Channel
- ngOnInit(): Call Channel page with 1 text(time_limit), 1 UsersList(users_list), 1 DirectMessagesList(dms_list), 1 input(snippet_content) and 2 buttons(snippet_send, sign_out).
- onClickSnippetSendButton(snippet_content: string): Send a snippet to backend.
- terminateChannel(): When the time limit of the channel is over, it eliminates all the data of the channel and redirect to ExpiredChannel page.
- onClickSignOutButton(): Sign out and redirect to SignIn page.
8. UserAccess - ngOnInit(): Call UserAccess page with 1 image(profile_picture), 1 input(nickname) and 1 button(user_access).  - onClickUserAccessButton(profile_picture: image, nickname: string): Call signIn in UserService. If sign-in is accepted, redirect to Channel page. If sign-in is rejected, alert the warning message.
9. ExpiredChannel - ngOnInit(): Call ExpiredChannel page with 1 image(bomb) and 1 text(description).

**Comment by hwan517h1** [comment]
**Frontend Algorithms: Subcomponents** 

1. UsersList
 - ngOnInit(): Call getUsers in UserService and show the list of users in the left side of Channel page at the initialization of the channel.
- getUsers(): Call getUsers in UserService.
- sortByAlarm(): Sort the list of users along alarms. Alarm means there are DMs between users and is shown by a green dot next to profile picture.
2. DirectMessagesList
- ngOnInit(): Call getDMByReceiver in DirectMessageService repeatedly and show alarms on the list of users.
- getDMsById(id: string): Call getDMByReceiver in DirectMessageService and show the list of snippets in the right side of Channel page when a user clicks other users on the list of users.
- setDMType(type: string): Set the type of a DM. It will be a notice or not.

**Comment by hwan517h1** [comment]
**Frontend Algorithms: Services**

1. UserService
 - signUp(email: string, password: string, key: string) → Promise<boolean>: Call backend API, and return the result.
- signIn(email: string, password: string) → Promise<boolean>: Call backend API, and return the result. - signOut()→ Promise<boolean>: Call backend API. - accessUser(profile_picture: image, nickname: string) → Promise<boolean>: Call backend signIn API, and return the result.
- getUsers() → Promise<string[]>: Call backend API to get the list of users.
- getUserById(id: string) → Promise<User>: Call backend API to get a specific user. 
2. ChannelService
 - createChannel(channel_name: string, channel_duration: date) → Promise<boolean>: Call backend API, and return the result.
 - terminateChannel() → Promise<boolean>: Call backend API, and return the result. 
- showTimeLimit() → Promise<Date>: Call backend API, and return the result.
3. DirectMessageService 
- getDMBySender(id: string) → Promise<DirectMessage>: Call backend API to get a specific DirectMessage using the id of sender.
- getDMByReceiver(id: string) → Promise<DirectMessage>: Call backend API to get a specific DirectMessage using the id of receiver.
- existConnection(id: string, id: string) → Promise<boolean>: Call backend API, and return the result.

**Comment by hwan517h1** [comment]
Frontend Relations

![image](https://user-images.githubusercontent.com/37106318/47270513-cb306000-d5a7-11e8-822a-0c0d7469820f.png)

**Comment by sdu6342** [comment]
Implementation Plan

Divide the project implementation into the pages that fulfill the requirements of the project.
- Sign Up: A page that allows users to sign up and log in.
- Main: A page that allows you to create a channel and move it to a channel or to a QR Code view.
- Channel: A page that allows the user to interact with other users
- Channel New: Input form in which the administrator can create a new channel
- Direct Message: A sub page that allows users to talk on a one-to-one basis.
- QR view: A page with QR code to enter the channel

The distribution of the view by sprint is as follows.
sprint 2: QR view, Main
sprint 3: Channel, New Channel
sprint 4: Direct Message
sprint 5: Sign Up

**Comment by KyoungWan** [comment]
## Testing Plan

We would set up our testing from sprint 3, 

We except our testing coverage up to 90%. 

Details are below

### Unit Testing

- Tools 
  - Angular
    -  Jasmine: Javascript testing framework
    - Karma: Test specific elements in Jasmine
    - Travis CI: Test integration of project 
  - Django
    - Python unit test
- Testing type
  - Unit test
    - We would test every single components and modules
  - Functional test
    - We would test RESTful APIS in MVC pattern.
    - We would test WebSocket protocol in our Chat service
  - Integration test
    - Wr eould test our user stories.
    - By using Travis CI, the integration test will force the code to merge successfully.
